### ISSUE TITLE
Rework "preview" screenshot solution

### ISSUE THREAD

**Issue by knalli** [knalli/electron-remote-dashboard#1]
Behind the scenes, this is simply using `electron-screenshot` [making an image of the current view](https://github.com/knalli/electron-remote-dashboard/blob/16977d2e5336bd9c9a4295fcc7e7b18e06543a45/app/scripts/index.js#L22-L31).

There are situations in which no screenshot is taken (the url `/.cache/current-view.png`) returns nothing). 
- Why?
- How can this be improved?

**Comment by tailorvj** [comment]
Hi, how are you? I've forked this project and implemented a new solution for this feature. You are welcome to clone and test on your own machine

https://github.com/tailorvj/fullpagedashboard-client/tree/0.1.1

I intend to to take this solution to a new direction, based on the work you have done. I'm very thankful for the messaging mechanism you have built. I've learned a lot from it. The current tagged branch is within the confines of your vision though. You can update your code with it if you like, but please pay attention that I've changed the README.md to reflect the future of my own solution and the app/index.html splash screen is rebranded. If you would like to merge, I can provide a branch with the original README and the old splash screen design. Please let me know. 

## Solution

Instead of using the broken electron-screenshot library, I'm using webContents.capturePage() and instead of saving it to /.cache/current-view.png, I'm sending it as base64 over the wire with socket.io. 

## Changelog for my current released version

https://github.com/tailorvj/fullpagedashboard-client/blob/0.1.1/README.md#changelog

Kind regards,
Tailor

**Comment by knalli** [comment]
@tailorvj  Thank you for getting in touch.

I will have a look into it at some later point, but so far thank you for notifying. I'm going with you, that you are planing something different (targeting FullPageDashboard) which is and was never my focus. Maybe both projects can still benefit each other.
